from pydantic import BaseModel, Field
from typing import List

# --- Input Schemas ---
class GenerateRequest(BaseModel):
    text_content: str = Field(..., description="The raw transcript or blog text to be processed.")
    brand_voice: str = Field(..., description="The tone of voice (e.g., Professional, Witty, Academic).")

class ReviewRequest(BaseModel):
    agent_id: str = Field(..., description="The ID of the agent whose output was edited (e.g., 'Agent-LI').")
    original_output: str = Field(..., description="The original output generated by the agent.")
    edited_output: str = Field(..., description="The new, human-edited output.")
    brand_voice: str = Field(..., description="The current brand voice.")
    analyst_context: dict = Field(..., description="The Big Idea and Atomic Hooks from The Analyst.")

# --- Analyst Schemas ---
class AtomicHook(BaseModel):
    hook: str = Field(..., description="A compelling, counter-intuitive, or highly valuable point.")

class AnalystOutput(BaseModel):
    big_idea: str = Field(..., description="The core narrative or 'Big Idea' (max 3 sentences).")
    atomic_hooks: List[AtomicHook] = Field(..., min_length=5, max_length=5, description="Exactly 5 Atomic Hooks.")

# --- Content Squad Schemas ---
class XPost(BaseModel):
    content: str = Field(..., description="The text of the post. Post 1 must be a scroll-stopping hook.")
    visual_placeholder: str | None = Field(None, description="Visual placeholder, e.g., '[VISUAL: Diagram of System Architecture]'")

class XGBThreadOutput(BaseModel):
    posts: List[XPost] = Field(..., min_length=10, max_length=10, description="A 10-post thread optimized for X.")

class LinkedInOutput(BaseModel):
    post_text: str = Field(..., description="A highly engaging 1,200-character LinkedIn post. Start with a hook. End with thoughts or CTA.")

class ShortsScene(BaseModel):
    timestamp_seconds: str = Field(..., description="e.g., '0-3s'")
    visual: str = Field(..., description="Visual instructions for the scene.")
    audio_speech: str = Field(..., description="The script or audio notes for the scene.")

class ShortsScriptOutput(BaseModel):
    scenes: List[ShortsScene] = Field(..., description="A fast-paced, 60-second video script broken into scenes (Hook, Retainer, CTA).")

class SubstackTakeaway(BaseModel):
    bullet_point: str = Field(..., description="An actionable or insightful takeaway.")

class SubstackOutput(BaseModel):
    introductory_synthesis: str = Field(..., description="A 'TL;DR' introduction synthesizing the main document.")
    takeaways: List[SubstackTakeaway] = Field(..., min_length=3, max_length=3, description="Exactly 3 bulleted takeaways.")
